// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIVPNQWeb3AEeNjOwhGbnz08C6npQH7qA',
    appId: '1:36214887046:web:9fedc6e7ae9da665aa7707',
    messagingSenderId: '36214887046',
    projectId: 'stockappcomp585',
    authDomain: 'stockappcomp585.firebaseapp.com',
    storageBucket: 'stockappcomp585.firebasestorage.app',
    measurementId: 'G-CFT058RWTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYVgPzMly_rBgmKXgFYHeAb34fFnjBq8k',
    appId: '1:36214887046:android:67ef58142cb2ad2aaa7707',
    messagingSenderId: '36214887046',
    projectId: 'stockappcomp585',
    storageBucket: 'stockappcomp585.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl8hCWl9vLPNTDtMwhRZyKDDcD6wywvmg',
    appId: '1:36214887046:ios:78e66a6563426a80aa7707',
    messagingSenderId: '36214887046',
    projectId: 'stockappcomp585',
    storageBucket: 'stockappcomp585.firebasestorage.app',
    iosBundleId: 'com.example.stockappflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl8hCWl9vLPNTDtMwhRZyKDDcD6wywvmg',
    appId: '1:36214887046:ios:78e66a6563426a80aa7707',
    messagingSenderId: '36214887046',
    projectId: 'stockappcomp585',
    storageBucket: 'stockappcomp585.firebasestorage.app',
    iosBundleId: 'com.example.stockappflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIVPNQWeb3AEeNjOwhGbnz08C6npQH7qA',
    appId: '1:36214887046:web:21f2e3ceefc3ae20aa7707',
    messagingSenderId: '36214887046',
    projectId: 'stockappcomp585',
    authDomain: 'stockappcomp585.firebaseapp.com',
    storageBucket: 'stockappcomp585.firebasestorage.app',
    measurementId: 'G-98R992WY42',
  );
}
